version: '3.4'

services:
  cache:
    image: redis
    command: redis-server --requirepass testPassword
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  eurekareg:
    image: steeltoeoss/eurekaserver

  identity.api:
    image: eshop/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sql.data
      - eurekareg
      
  catalog.api:
    image: eshop/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - eurekareg
      - rabbitmq    

  web:
    image: eshop/web:${TAG:-latest}
    build:
      context: .
      dockerfile: src/UI/Web/Dockerfile
    depends_on:
      - sql.data
      - eurekareg

